import Head from 'next/head'
import Navigation from './Navigation';
function Header() {
    return ( 
        <>
        <Head>
        <title>Portfolio!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/portfolio-modified.png" />
        </Head>
       
        </>
     );
}

export default Header;